### ISSUE TITLE
Directions Unclear

### ISSUE THREAD

**Issue by storywr** [learn-co-curriculum/namespaced-routes-lab#16]
It was pretty unclear that there was only going to be 1 instance of Preference rather than a preference associated w each artist/song with a has_many belongs_to relationship.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
