### ISSUE TITLE
Test don't run out of order.

### ISSUE THREAD

**Issue by snsavage** [learn-co-curriculum/namespaced-routes-lab#17]
Running a single feature spec file or individual specs causes the error "Uninitialized Constant Artist".  This has something to do with how the database cleaning is being handled.  The specs should be able to run independently by file and by spec.

**Comment by drakeltheryuujin** [comment]
Hi @snsavage,

Thanks for this feedback. We can investigate this particular suggestion for a future release for this track. Thanks for contributing! 💙
