### ISSUE TITLE
These labs are getting really awful, just not even worth opening

### ISSUE THREAD

**Issue by scottibe** [learn-co-curriculum/namespaced-routes-lab#18]
You really should redo the whole rails section

**Comment by gj** [comment]
Hi @scottibe !

The issue title makes me sad. 🙁

We know that the Rails section needs some love. It's on the docket!

Do you have any suggestions — either for temporary fixes or more permanent solutions once we're able to give the section some proper attention — for how the curriculum could be improved?

Thanks!

**Comment by drakeltheryuujin** [comment]
I don't have enough information to go on, so I'm going to close it for now. If you can provide further detail about what could be improved upon in this lab, feel free to re-open this issue and we can prioritize updates for another release of this curriculum.

As always, thanks for contributing! 💙
