### ISSUE TITLE
Lab unclear

### ISSUE THREAD

**Issue by gb23** [learn-co-curriculum/namespaced-routes-lab#20]
I already made a comment on someone else's issue here, but I wanted to create an individual issue because I am not sure if the curriculum team is alerted based on new issues raised, or new comments.  It's pretty clear by the number of issues students have raised about this lab that the curriculum people need to be alerted.  

The instructions are terribly unclear.  It's frustrating because I really want to practice my skills on the topic.

**Comment by drakeltheryuujin** [comment]
See #19 for additional feedback. 

If you can provide further detail about what could be done to make this lab more clear, feel free to re-open this issue and we can prioritize updates for another release of this curriculum.

As always, thanks for contributing! 💙
