### ISSUE TITLE
No specs for requirement 7

### ISSUE THREAD

**Issue by KatieLars** [learn-co-curriculum/namespaced-routes-lab#21]
Hello! I didn't see any specs for the 7th requirement (regarding the ordering of artists and songs according to a preference). Also, some explanation about the relationship between preferences and the other models would be useful . . .

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback about the spec.
We have updated the materials and believe your issue to have been resolved.
Thanks for contributing! 💙
