### ISSUE TITLE
FYI : Readme instructions and forked lab tests are not 100% consistent

### ISSUE THREAD

**Issue by raiet13** [learn-co-curriculum/namespaced-routes-lab#22]
Situation : After reading the readme, I then follow the tests and only refer back to the readme if I get stuck and am searching for further information.

Issue? : I reached the end of the "failed" tests and noticed (after checking because I briefly thought I was going crazy) that the "7) Update the artists and songs index pages to order by name according to each preference" instruction did not have a test.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
Thanks for contributing! 💙
