### ISSUE TITLE
tests passed w/o correct code

### ISSUE THREAD

**Issue by BrittanyTinnin** [learn-co-curriculum/namespaced-routes-lab#24]
my tests passed and I checked the solutions after.. and there's a bunch of code in the controllers that I did have to put in for the tests to pass .. just FYI

**Comment by drakeltheryuujin** [comment]
Hi there,

I would need more information to reproduce this issue, so I'm going to close it for now. . There may be missing tests or just extraneous code.

If you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment (local or IDE), I'd be happy to take a second look!

As always, thanks for contributing! 💙
