### ISSUE TITLE
#7 on README is wrong?

### ISSUE THREAD

**Issue by JoeQuattrone** [learn-co-curriculum/namespaced-routes-lab#25]
> Update the artists and songs index pages to order by name according to each preference.

From the directions on the README it seems like you want us to update the Artist and Song index views. However, the tests did not test for views and the solution did not make changes to the view pages so this direction is confusing.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
