### ISSUE TITLE
gem dependency issues, unable to run specs

### ISSUE THREAD

**Issue by morgvanny** [learn-co-curriculum/namespaced-routes-lab#26]
When you first try to run the tests, you get this error:

> An error occurred while loading ./spec/controllers/admin/preferences_controller_spec.rb.
> Failure/Error: require File.expand_path('../../config/environment', __FILE__)
> 
> LoadError:
>   cannot load such file -- active_storage/engine

My students let me know that using the latest version of rails instead of 5.0.7.1, and adding `gem 'listen'` to the gemfile will fix this issue, but I'm not sure why that works exactly, or if that's a solution that will work in perpetuity.

#staff

**Comment by swarbrick85** [comment]
this didn't work

**Comment by gac2117** [comment]
This worked for me too. I took out the version number for rails and added `gem 'listen'` to the development group of my Gemfile and ran `bundle update`

**Comment by drakeltheryuujin** [comment]
This one was a doozy. I've updated the materials based on these answers and I believe this has been resolved.

Hopefully, other students won't have this problem anymore. If you do not believe that this issue has been addressed, please re-open this issue. 💙
