### ISSUE TITLE
Line 43 in Songs_controller_spec

### ISSUE THREAD

**Issue by swarbrick85** [learn-co-curriculum/namespaced-routes-lab#27]
In this spec file i commented out line 43 because, according to the tech coach, the code is doing what it's supposed to be doing, but the test is still not passing. 

Failures:

  1) SongsController GET show with  artist redirects to artists songs when artist song not found
     Failure/Error: expect(controller).to set_flash[:alert]
     
     NameError:
       undefined local variable or method `set_flash' for #<RSpec::ExampleGroups::SongsController::GETShowWithArtist:0x007fab86807850>
     # ./spec/controllers/songs_controller_spec.rb:43:in `block (3 levels) in <main>'

**Comment by RoseBrennan** [comment]
I'm encountering the same issue.

**Comment by morgvanny** [comment]
it appears that adding this into the rails_helper.rb file in the spec directory should fix this, according to this https://github.com/thoughtbot/shoulda-matchers/issues/903

Shoulda::Matchers.configure do |config|
  config.integrate do |with|
    with.test_framework :rspec
    with.library :rails
  end
end

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved in commit #7516a6.
We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
