### ISSUE TITLE
Clone error

### ISSUE THREAD

**Issue by Lukeghenco** [learn-co-curriculum/namespaced-routes-lab#3]
this cloned lab has almost all of the steps already finished for us.

**Comment by jmburges** [comment]
@blake41 any ideas what's up with this lab?

**Comment by AnnJohn** [comment]
cc' @scottcreynolds

**Comment by jmburges** [comment]
Yup! our mistake. Thanks for catching it. Fixed with commit dc603ead3861e758cc7f0b8bdd128e89529db1f2
