### ISSUE TITLE
I think a test may be missing to check for ASC or DESC order.

### ISSUE THREAD

**Issue by BSalemi** [learn-co-curriculum/namespaced-routes-lab#34]
#6 On this lab's ReadMe states: 

_Create a PreferencesController, routes, and views to manage the preferences. Do this under an Admin module to separate it from the standard user functionality. The artists and songs index pages should order by name according to each preference._

However, there are no requirements that we put anything in the index pages to order the songs/artist by name. I may be misinterpreting what #6 is saying, but I assumed there would be some sort of test to check **Preference.song_sort_order** and **Preference.artist_sort_order**.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
