### ISSUE TITLE
The instructions are suppppper low level

### ISSUE THREAD

**Issue by jmburges** [learn-co-curriculum/namespaced-routes-lab#4]
Maybe we can bring the instructions up a level? So more like user stories, and less prescriptive?

@blake41

**Comment by AnnJohn** [comment]
cc' @scottcreynolds

**Comment by coltonstaab1** [comment]
Yes, totally agreed. I think it becomes clear over the course of the lab what you're trying to achieve, but it's not at all clear what the objective of the lab is at the outset

**Comment by pletcher** [comment]
@scottcreynolds If you get a chance, could really use a hand on this one. I'm not super familiar with this lab, so I'm wary of attempting a rewrite and possibly removing valuable information.

**Comment by scottcreynolds** [comment]
@pletcher yep this one is on my list
