### ISSUE TITLE
Solution already supplied. 

### ISSUE THREAD

**Issue by frankNowinski** [learn-co-curriculum/namespaced-routes-lab#6]
I don't know if this was intentional or not but the majority of the solution for this lab was already completed. The only code I had to write in order to pass all of the tests was only what was declared in Number 4 of the instructions: 

4. Update the artists#index action to order by name with artist_sort_order and the songs#index action to order songs by title with song_sort_order. Make sure to check that the value exists and set it to the default if it doesn't.

**Comment by jmburges** [comment]
Yup! our mistake. Thanks for catching it. Fixed with commit dc603ead3861e758cc7f0b8bdd128e89529db1f2
